---
title: "2020 SEC"
author: "Ananda Biswas"
date: "`r Sys.Date()`"
output: html_document
---
```{r}
# Q 1. (m)
student_names <- c("Ananda", "Debarghya", "Nitesh", "Ranit", "Romit")
student_marks <- c("50", "55", "49", "51", "48")

my_data_frame <- data.frame(student_names, student_marks)
my_data_frame

new_students <- c("Teesha", "Ripan")
new_marks <- c("45", "45")

new_data_frame <- data.frame(new_students, new_marks)
new_data_frame

# rbind(my_data_frame, new_data_frame) this will throw an error as the column names of my_data_frame and new_data_frame are not same

rbind(my_data_frame, setNames(new_data_frame, names(my_data_frame)))
```
```{r}
data <- 1:12
my_mat <- matrix(data, nrow = 3, ncol = 4, byrow = TRUE)

my_mat

new <- c(rep(1, 4))

rbind(my_mat, setNames(new, names(my_mat)))
```

```{r}
# Q 1. (n)
round(pi, digits = 5)
```

```{r}
# Q 1. (o)
a <- matrix(c(2, 3, 4, 5), nrow = 2, ncol = 2, byrow = TRUE)
eigen(a)$vectors
```

```{r}
# Q 1. (q)
x <- factor(c(2, 6, 4, 2, 4, 4, 6))
x # this prints the vector and the levels
# levels(x) # this prints the levels of the vector x
```


```{r}
# Q 2. (g)
slices <- c(2217, 2085, 3090, 295, 3173, 2575)

sector_names <- c("Agriculture", "Power", "Large Industry", "Small Industry", "Communication", "Miscellaneous")

sector_colors <- c("Green", "Grey", "Blue", "Pink", "Red", "Yellow")

percentages <- round((slices/sum(slices))*100)

tags <- paste(percentages, "%", sep = " ")

pie(slices,
    col = sector_colors,
    labels = tags,
    main = "Expenditure in the Public Sector during the 4th Five-year Plan")

legend("bottomleft",
       legend = sector_names,
       fill = sector_colors,
       cex = 0.8,
       bty = "n")
```

```{r}
# Q. 2. (h)
random_normal_sample <- rnorm(100)

random_normal_sample

quantile(random_normal_sample)
```




```{r}
# Q. 3. (c) (i)
number_of_students <- c(22400, 14600, 6000)

places <- c("Kolkata", "Outside Kolkata but within W.B.", "Outside W.B.")

colors <- c("Blue", "Lightblue", "Red")

percentages <- round((number_of_students/sum(number_of_students))*100)

tags <- paste(percentages, "%", sep = " ")

pie(number_of_students,
    labels = tags,
    col = colors,
    main = "Students in the Colleges in Kolkata - 2001")

legend("topleft",
       fill = colors,
       legend = places,
       cex = 0.7,
       bty = "n")
```


```{r}
x <- seq(from = 0.00, to = 1.0, by = 0.01)

y <- pnorm(x)

my_df <- data.frame(x, F = y)
my_df
```

