---
title: "Autocorrelation Function"
author: "Ananda Biswas"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r}
our_data <- c(1.6, 0.8, 1.2, 0.5, 0.9, 1.1, 1.1, 0.6, 1.5, 0.8, 0.9, 1.2, 0.5, 1.3, 0.8, 1.2)

print(length(our_data))

print(our_data)

mean(our_data)
```

```{r}
x <- our_data[-length(our_data)]

print(length(x))

print(x)
```

```{r}
y <- our_data[-1]

print(length(y))

print(y)
```

```{r}
z <- y[-1]

print(length(z))

print(z)
```

```{r}
u <- z[-1]

print(length(u))

print(u)
```


```{r}
a <- x - mean(our_data)

b <- y - mean(our_data)

c <- a * b

print(c)

sum(c)
```

```{r}
d <- x[-length(x)]

e <- d - mean(our_data)

f <- z - mean(our_data)

g <- e * f

print(g)

sum(g)
```

```{r}
h <- d[-length(d)]

i <- h - mean(our_data)

j <- u - mean(our_data)

k <- i * j

print(k)

print(sum(k))
```

```{r}
sum_of_deviation_squares <- sum((our_data - mean(our_data))^2)

sum_of_deviation_squares
```

```{r}
round(sum(c) / sum_of_deviation_squares, digits = 2)

sum(g) / sum_of_deviation_squares

round(sum(k) / sum_of_deviation_squares, digits = 2)
```