---
title: "dataframe"
author: "Ananda Biswas"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
# creating a data frame from vectors as columns

papers <- c("Paper I", "Paper II", "Paper III", "Paper IV")
marks_in_sem_1 <- c(86, 94, 92, 82)
marks_in_sem_2 <- c(60, 65, 67, 79)

my_dataframe <- data.frame(papers, marks_in_sem_1, marks_in_sem_2)
my_dataframe


# customizing the column names
my_dataframe <- data.frame(PAPER = papers, MARKS_1 = marks_in_sem_1, MARKS_2 = marks_in_sem_2)
my_dataframe
```

```{r}
# attach() function

attach(quakes)

summary(depth)
summary(mag)

```

```{r}
attach(mtcars)

# help(mtcars)

car_weights <- wt
car_fuel_consumption <- mpg

mean(car_weights)
mean(car_fuel_consumption)
```

```{r}
# apply() function

my_dataframe <- trees
my_dataframe

apply(trees, 2, mean)
```


```{r}
marks_in_sem_1 <- c(86, 94, 92, 82)
marks_in_sem_2 <- c(60, 65, 67, 79)

dataframe_1 <- data.frame(A1 = marks_in_sem_1, A2 = marks_in_sem_2)

dataframe_1

apply(dataframe_1, 1, mean) # gives the mean of each of the 4 rows of the dataframe

apply(dataframe_1, 2, sum) # gives the sum of each of the 2 columns of the dataframe


```

```{r}
apply(quakes[,3:4], 2, summary)
```

```{r}
apply(mtcars[,1:8], 2, mean)
```

```{r}
y <- matrix(data = c(1, 4, 1, 0, 2, -1), nrow = 2, ncol = 3, byrow = TRUE)
y

apply(y[,2:3], 1, mean) # gives the row wise mean of the 2nd and 3rd column


apply(y[,2:3], 2, mean) # gives the column wise mean of the 2nd and 3rd column
```

```{r}
papers <- c("Paper I", "Paper II", "Paper III", "Paper IV")
marks_in_sem_1 <- c(86, 94, 92, 82)
marks_in_sem_2 <- c(60, 65, 67, 79)

my_dataframe <- data.frame(papers, marks_in_sem_1, marks_in_sem_2)
my_dataframe

rownames(my_dataframe) <- c("R1", "R2", "R3", "R4")
my_dataframe

colnames(my_dataframe) <- c("C1", "C2", "C3")
my_dataframe
```

```{r}
top.bacon.searching.cities <- data.frame(
      city = c("Seattle", "Washington", "Chicago",
                "New York", "Portland", "St Louis",
                "Denver", "Boston","Minneapolis", "Austin",
                "Philadelphia", "San Francisco", "Atlanta",
                "Los Angeles", "Richardson"),
      rank = c(100, 96, 94, 93, 93, 92, 90, 90, 89, 87,
                85, 84, 82, 80, 80)
      )

top.bacon.searching.cities

typeof(top.bacon.searching.cities)

class(top.bacon.searching.cities)
```