---
title: "lines"
author: "Ananda Biswas"
date: '`r Sys.Date()`'
output: html_document
---

```{r}
a <- 1:5
b <- c(4, 2, 3, 1, 5)
plot(a, b, type = "l")
```

```{r}
plot(pressure) # this is scatterplot, not line plot
```

```{r}
plot(pressure, type = "l") # this is line plot
```

```{r}
plot(pressure, type = "l", lty = 1, lwd = 2, col = "red")
```

```{r}
for (i in 0:6) {
  heading = paste("Line Plot", "lty = ", i)
  plot(pressure, 
       type = "l", 
       lty = i, 
       lwd = 2, 
       col = "red", 
       main = heading)
}

```


```{r}
# multiple lines in one plot

# first dataset
x1 <- seq(from = 0, to = 8, by = 2)
y1 <- c(4, 5, 1, 3, 2)

# second dataset
x2 <- seq(from = 1, to = 9, by = 2)
y2 <- c(2, 3, 4, 1, 5)

x_limits <- range(c(x1, x2))
y_limits <- range(c(y1, y2))

plot(x1, y1, 
     xlim = x_limits,
     ylim = y_limits,
     type = "l",
     lty = 5,
     lwd = 2,
     col = "red",
     xlab = "X",
     ylab = "Y")

lines(x2, y2, lty = 5, lwd = 2, col = "blue")

legend(0.25, 3.5, c("y1", "y2"), lty = 5, lwd = 2, col = c("red", "blue"), bty = "n")
```