---
title: "Mathematical Ludo Example 2"
author: "Ananda Biswas"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
params:
  number_of_times_you_want_to_play: n
---

```{r}
# n = as.numeric(readline(prompt = "Enter the number of times you want to play = "))
n <- as.integer(params$number_of_times_you_want_to_play)
```


```{r}
i = 1

numbers <- c()

while(i <= n){
  numbers[i] = floor(runif(n = 1, min = 1, max = 5))
  
  i = i + 1
}
```


```{r}
x <- c(0)
y <- c(0)

i = 2

while (i <= n+1) 
{
  if(numbers[i-1] == 1)
  {
    x[i] <- 0
    y[i] <- ( 0.16 * y[i-1])
  }
  else if(numbers[i-1] == 2)
  {
    x[i] <- ( (0.85 * x[i-1]) - (0.04 * y[i-1]) )
    y[i] <- ( ( (-0.04) * x[i-1]) + (0.85 * y[i-1]) + 1.6 )
  }
  else if(numbers[i-1] == 3)
  {
    x[i] <- ( (0.2 * x[i-1]) - (0.26 * y[i-1]) )
    y[i] <- ( (0.23 * x[i-1]) + (0.22 * y[i-1]) + 1.6)
  }
  else if(numbers[i-1] == 4)
  {
    x[i] <- ( ( (-0.15) * x[i-1] ) + (0.28 * y[i-1]) )
    y[i] <- ( (0.26 * x[i-1]) + (0.24 * y[i-1]) + 0.44)
  }
  
  i = i + 1
}
```


```{r}
plot(x, y,
     xlab = "abscissas",
     ylab = "ordinates",
     main = "Mathematical Ludo Example 2",
     pch = 19,
     cex = 0.5)
```