---
title: "probability_distributions"
author: "Ananda Biswas"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
# 10C2
choose(10, 2)
```

```{r}
# generating all possible combinations
combn(1:5, 3) # all possible combinations of 1, 2, 3, 4, 5 taken 3 at a time
```

*UNIFORM DISTRIBUTION*
```{r}
# generating 10 numbers following U(1, 20)
runif(n = 10, min = 1, max = 20)


# to find P[X=5] when X~U(1, 20)
dunif(5, min = 1, max = 20)


# to find log(P[X=5]) when X~U(1, 20)
dunif(5, min = 1, max = 20, log = TRUE)


# to find F(X) for any X=x i.e. the value of the distribution function
# F(3) i.e. P[X <= 3]
punif(q = 3, min = 1, max = 20, lower.tail = TRUE, log.p = FALSE) 


# to find P[X > 3]
punif(q = 3, min = 1, max = 20, lower.tail = FALSE, log.p = FALSE)


# to find log(F(X))
# log(F(3))
punif(q = 3, min = 1, max = 20, lower.tail = TRUE, log.p = TRUE) 


# to find the value of Quartile Function
# Let Q be the quartile function, then Q(x) is such a value that 
# P(X <= Q(x)) = x
# by qunif() function, we provide 0<x<1 to get Q(x)
# let t be the output of qunif()
# then we must have P(X <= t) = x, we can verify that by punif() function

# 1st quartile
qunif(p = 0.25, min = 1, max = 20, lower.tail = TRUE, log.p = FALSE)
# punif(q = 5.75, min = 1, max = 20, lower.tail = TRUE, log.p = FALSE)

# 1st percentile
qunif(p = 0.05, min = 1, max = 20, lower.tail = TRUE, log.p = FALSE)


qunif(p = 0.6, min = 1, max = 20, lower.tail = TRUE, log.p = FALSE)
```


*BINOMIAL DISTRIBUTION*
```{r}
# generating 10 random numbers that follow B(50, 0.75)
rbinom(n = 10, size = 50, prob = 0.75)



# finding probability
# P[X = 7] when X ~ B(10, 0.5)
dbinom(x = 7, size = 10, prob = 0.5, log = FALSE)



# Cumulative Distribution Function
# P[X <= 15]
pbinom(q = 15, size = 50, prob = 0.75, lower.tail = TRUE, log.p = FALSE)



# Quantile Function
qbinom(p = 0.25, size = 50, prob = 0.75, lower.tail = TRUE, log.p = FALSE)




# we want to find P(5 <= X <= 8) where X ~ B(12, 0.4)

# P(5 <= X <= 8) = P(5) + P(6) + P(7) + P(8)

# method 1 - evaluate F(8) - F(4)
pbinom(8, 12, 0.4) - pbinom(4, 12, 0.4)

# method 2 - evaluate P(5) + P(6) + P(7) + P(8)
sum(dbinom(5:8, 12, 0.4))
```


*POISSON DISTRIBUTION*
```{r}
rpois(20, lambda = 1.5)

dpois(x = 0, 1.5, log = FALSE)

ppois(q = 2, lambda = 1.5, lower.tail = TRUE, log.p = FALSE)

qpois(p = 0.25, lambda = 1.5, lower.tail = TRUE, log.p = FALSE)
```


*NORMAL DISTRIBUTION*
```{r}
rnorm(n = 10, mean = 2, sd = 1.5)

dnorm(x = 2, mean = 2, sd = 1.5, log = FALSE)

pnorm(q = 20, mean = 12, sd = 4, lower.tail = TRUE, log.p = FALSE)

pnorm(q = 20, mean = 12, sd = 4, lower.tail = FALSE, log.p = FALSE)

sum(dnorm(26:40, mean = 30, sd = 5, log = FALSE))

pnorm(q = 45, mean = 30, sd = 5, lower.tail = FALSE, log.p = FALSE)

qnorm(p = 0.25, mean = 30, sd = 5, lower.tail = TRUE, log.p = FALSE)
```