ratings_data <- read.csv("D:\\data_sets\\cc12_prac_q3_data.csv", stringsAsFactors = TRUE)
dim(ratings_data)
names(ratings_data)
class(ratings_data$rater)
class(ratings_data$service_station)
class(ratings_data$ratings)
ratings_anova <- aov(ratings ~ rater + service_station, data = ratings_data)
summary(ratings_anova)
TukeyHSD(ratings_anova)