\documentclass[11pt, a4paper]{article}

\usepackage[top = 1 in, bottom = 1 in, left = 0.8 in, right = 0.8 in]{geometry}
\usepackage{amsmath, amssymb, amsfonts}

\allowdisplaybreaks[4]

\usepackage{enumerate}
\usepackage{array}
\usepackage{multirow}
\usepackage{fontawesome5}
\usepackage{tasks}
\usepackage{bbding}
\usepackage{undertilde}
\usepackage{twemojis}
% how to use bull's eye ----- \scalebox{2.0}{\twemoji{bullseye}}
\usepackage{fontspec}
\usepackage{fancyhdr}
\usepackage{lastpage}
\usepackage{mathrsfs}
\usepackage{pifont}
\usepackage{hyperref}

\pagestyle{fancy}
\fancyhf{}
\fancyfoot[C]{Page \thepage\ of \pageref{LastPage}}
\renewcommand{\headrulewidth}{0pt}

\title{MSMS 408 : Practical 18}
\author{{\fontsize{25}{20} \benyorithafont Ananda Biswas} \\[1em] Exam Roll No. : 24419STC053}
\date{\today}

\newfontface\benyorithafont{Benyoritha-G334D.otf}

\newfontface\myfont{Myfont1-Regular.ttf}[LetterSpace=0.05em]

\newfontface\cbfont{CaveatBrush-Regular.ttf}
% how to use --- \myfont --write text here--

\newfontface\gloriahallelujahfont{GLORIAHALLELUJAH-REGULAR.TTF}

\newcommand{\bs}[1]{\boldsymbol{#1}}

\begin{document}

\maketitle


\section*{\faArrowAltCircleRight[regular] \textcolor{blue}{Question}}

\begin{enumerate}[(i)]
\item Generate a sample of size $1000$, each denoting the number of heads from $10$ tosses of \textit{either} a biased coin A with probability $0.4$ \textit{or} a biased coin B with probability $0.6$. $P_A(\text{Head}) = \theta_A = 0.3$, $P_B(\text{Head}) = \theta_B = 0.8$ be the respective bias of the coins A and B.

Assume that you are given only $h_i$'s and you don't know which of the two coins each $h_i$ comes from.

\item Use Expectation-Maximization algorithm to estimate the mixing proportion, $\phi$, say and the bias $\theta_A$, $\theta_B$.

\item Show the parameter updates and increase in log-likelihood in successive iterations.

\item Using the parameter estimates, predict which coin each $h_i$ might have been generated from.
\end{enumerate}


\section*{\faArrowAltCircleRight[regular] \textcolor{blue}{Theory}}

\vspace{1cm}

\begin{enumerate}

\item[\scalebox{2.0}{\twemoji{keycap: 1}}] \hspace{0.2cm} Data simulation :

\begin{itemize}
\item Generate $u_1, \ldots, u_n \sim U(0, 1)$.

\item Set $$\forall i = 1(1)n, \; h_i = \begin{cases} x \sim \text{Binomial}(10, 0.3) \text{ if } u_i <= 0.4 \\[0.5em] x \sim \text{Binomial}(10, 0.8)\text{ if } u_i > 0.4 \end{cases}.$$
\end{itemize}

\newpage

\item[\scalebox{2.0}{\twemoji{keycap: 2}}] \hspace{0.2cm} EM Algorithm :

\begin{itemize}
\item $\bs{\theta} = \left\{ \phi, \theta_A, \theta_B \right\}$.

\item Start with an initial value $\bs{\theta}^{(0)}$.

\item Repeat until convergence $\left\{ \right.$

\begin{align*}
&\text{(E-Step) } 
\begin{aligned}[t]
\text{For each } i &: \\[1em]
\gamma^{(i)} &:= P \left( z^{(i)} = A \mid h_i, \bs{\theta}^{(t)} \right) \\[1em]
1 - \gamma^{(i)} &:= P \left( z^{(i)} = B \mid h_i, \bs{\theta}^{(t)} \right)
\end{aligned}\\[1em]
&\text{(M-Step) } 
\begin{aligned}[t]
\text{Update} &: \\[1em]
\hspace{-2em}\phi &:= \dfrac{1}{n} \sum \limits_{i=1}^{n}\gamma^{(i)}, \\[1em]
{\theta}_A &:= \dfrac{\sum \limits_{i = 1}^{n} \gamma^{(i)} h_i}{\sum \limits_{i = 1}^{n} \gamma^{(i)} \cdot (h_i + t_i)}, \\[1em]
{\theta}_B &:= \dfrac{\sum \limits_{i=1}^{n} (1 - \gamma^{(i)}) \cdot h_i}{\sum \limits_{i=1}^{n} (1 - \gamma^{(i)}) \cdot (h_i + t_i)}
\end{aligned}
\end{align*}

$\left. \right\}$.
\end{itemize}

\item[\scalebox{2.0}{\twemoji{keycap: 3}}] \hspace{0.2cm} Predict 

$$x^{(i)} \in 
\begin{cases} \text{Coin A if } \gamma^{(i)} > 1 - \gamma^{(i)} \\[0.5em]
              \text{Coin B if } \gamma^{(i)} \leq 1 - \gamma^{(i)}
\end{cases}$$

where $\gamma^{(i)}, 1 - \gamma^{(i)}$ are evaluated on the final estimates of $\bs{\theta}$.

\end{enumerate}

\section*{\faArrowAltCircleRight[regular] \textcolor{blue}{R Program}}


<<echo=FALSE>>=
rm(list = ls())
@

<<echo=FALSE>>=
set.seed(14)
@

\begin{enumerate}

\item[\scalebox{2.0}{\twemoji{keycap: 1}}]

<<>>=
true.theta <- c(0.4, 0.3, 0.8)
@

<<>>=
true.phi <- true.theta[1]
true.theta.A <- true.theta[2]; true.theta.B <- true.theta[3]
@

<<>>=
x <- c()
@

<<>>=
n <- 1000
@

<<>>=
u <- runif(n)
@

<<>>=
x <- ifelse(u <= true.phi, rbinom(n, 10, true.theta.A), rbinom(n, 10, true.theta.B))
@

<<>>=
head(x)
@

\item[\scalebox{2.0}{\twemoji{keycap: 2}}]

<<>>=
theta <- c(0.9, 0.5, 0.6)
@

<<>>=
epsilon <- 0.00001
@

<<>>=
theta.history <- list(); iter <- 1
@

<<>>=
repeat{
  # Current Setting
  phi <- theta[1]
  thetaA <- theta[2]; thetaB <- theta[3]
  
  # E-Step
  joint.prob <- matrix(NA, nrow = n, ncol = 2)
  joint.prob[,1] <- dbinom(x, size = 10, prob = thetaA) * phi
  joint.prob[,2] <- dbinom(x, size = 10, prob = thetaB) * (1 - phi)
  
  marginal.prob <- rowSums(joint.prob)
  
  posterior.prob <- joint.prob / marginal.prob
  
  
  # M-Step
  theta.new <- c()
  
  # update phi
  theta.new[c(1)] <- colMeans(posterior.prob)[1]
  
  # update thetaA
  theta.new[c(2, 3)] <- colSums(posterior.prob * x) / colSums(posterior.prob * 10)
  
  theta.history[[iter]] <- theta.new
  iter <- iter + 1
  
  if(max(abs(theta - theta.new)) < epsilon){
    theta <- theta.new
    break
  }else{
    theta <- theta.new
  }
}
@

<<>>=
theta
@

\item[\scalebox{2.0}{\twemoji{keycap: 3}}]

<<>>=
df1 <- data.frame(do.call(rbind, theta.history))
colnames(df1) <- c("phi", "theta.A", "theta.B")
rownames(df1) <- paste("Iteration ", 1:(iter-1))
@

<<echo=FALSE, warning=FALSE, message=FALSE>>=
library(stargazer)
@

<<echo=FALSE, results='asis'>>=
stargazer(df1, summary = FALSE, rownames = TRUE,
          label = "Table 1",
          title = "Estimates in Successive Iterations",
          digits = 6)
@

<<>>=
log.likelihood.single <- function(theta, h){
  a <- theta[1] * dbinom(h, size = 10, prob = theta[2])
  b <- (1 - theta[1]) * dbinom(h, size = 10, prob = theta[3])
  
  return(log(a+b))
}
@

<<>>=
log.likelihood <- function(theta) sum(log.likelihood.single(theta, x))
@

<<>>=
log.likelihood.history <- apply(df1, 1, log.likelihood)
@

<<echo=FALSE, warning=FALSE, message=FALSE>>=
library(tidyverse)
@

<<>>=
df2 <- data.frame(iteration = 1:(iter-1),
           log.likelihood = log.likelihood.history)
@

<<>>=
df2 %>%
  ggplot(aes(x = iteration, y = log.likelihood)) +
  geom_line(linewidth = 1, col = "blue") +
  geom_point(size = 3, col = "red") +
  labs(x = "Iteration", y = "Log-likelihood", title = "EM Convergence")
@

\item[\scalebox{2.0}{\twemoji{keycap: 4}}] \hspace{0.2cm} We now calculate the posterior probabilities using the latest setting of the parameters, hence provide an estimate of which Gaussian each $h_i$ might belong to.

<<>>=
phi <- theta[1]
thetaA <- theta[2]; thetaB <- theta[3]
@

<<>>=
joint.prob <- matrix(NA, nrow = n, ncol = 2)
joint.prob[,1] <- dbinom(x, size = 10, prob = thetaA) * phi
joint.prob[,2] <- dbinom(x, size = 10, prob = thetaB) * (1 - phi)
@  

<<>>=  
marginal.prob <- rowSums(joint.prob)
@
 
<<>>=
posterior.prob <- joint.prob / marginal.prob
@

<<>>=
head(posterior.prob)
@

<<>>=
assignment <- data.frame(sample = x,
                         predicted.coin = ifelse(max.col(posterior.prob) == 1, 
                                                 "A", "B"))
@

<<results='asis', echo=FALSE>>=
stargazer(assignment[1:10,], summary = FALSE, rownames = FALSE,
          label = "Table 1",
          title = "Assignment to Coins")
@

\end{enumerate}

\newpage

\section*{\faArrowAltCircleRight[regular] \textcolor{blue}{Conclusion}}

\begin{table}[!htbp]
\def\arraystretch{1.5}

\centering
\begin{tabular}{ccc}
\hline
Parameter & Estimate & True Value \\[0.5em]
\hline \\[-0.8em]

$\widehat{\phi}$ 
& \Sexpr{round(theta[1], digits = 3)} 
& \Sexpr{true.theta[1]} \\[1em]

$\widehat{\theta_A}$ 
& \Sexpr{round(theta[2], digits = 3)} 
& \Sexpr{true.theta[2]} \\[1em]

$\widehat{\theta_B}$ 
& \Sexpr{round(theta[3], digits = 3)} 
& \Sexpr{true.theta[3]} \\[1em]

\hline
\end{tabular}
\caption{Estimated and true parameter values}
\end{table}

\vspace{1cm}

{\fontsize{25}{20} \ding{46}} \hspace{0.1cm} {\fontsize{12}{20}\gloriahallelujahfont Even though EM algorithm has a tendency to converge to the local optima, it has performed considerably well in our problem.}

\end{document}